version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Build application
                command: npm install
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Test application
                command: npm run test
            - store_artifacts:
                path: __tests__/coverage
workflows:
  development_buid_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
